<a href="https://colab.research.google.com/github/akshitasankhwar/pwdatascience/blob/master/Gen_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Generative AI – Text Generation and Machine Translation Assignment  
**Assignment Code: DS-AG-031**

---

# Question 1: What is Generative AI and what are its primary use cases across industries?

**Answer:**

Generative AI is a type of artificial intelligence that can create new content such as text, images, audio, video, or code by learning patterns from existing data. Instead of only analyzing or classifying data, generative models learn the underlying distribution of data and generate new samples that resemble the original dataset.

Common generative models include:
- Generative Adversarial Networks (GANs)
- Variational Autoencoders (VAEs)
- Transformer-based models like GPT

**Primary Use Cases Across Industries**

1. **Healthcare**
   - Drug discovery
   - Synthetic medical data generation
   - Automated medical report generation

2. **Finance**
   - Fraud scenario simulation
   - Financial report generation
   - Risk prediction models

3. **Media and Entertainment**
   - Story writing
   - Music and poetry generation
   - Video game content generation

4. **Marketing**
   - Advertisement copy generation
   - Product description writing
   - Personalized marketing campaigns

5. **Software Development**
   - Code generation
   - Debugging assistance
   - Documentation writing

6. **Education**
   - AI tutors
   - Automatic quiz generation
   - Learning content creation

---

# Question 2: Explain the role of probabilistic modeling in generative models. How do these models differ from discriminative models?

**Answer:**

Probabilistic modeling is fundamental in generative models because these models learn the probability distribution of the data. The goal is to understand how the data is generated so the model can create new samples that follow the same distribution.

Generative models learn the **joint probability distribution** of the data:

\[
P(X, Y)
\]

or sometimes just

\[
P(X)
\]

where **X** represents input data and **Y** represents labels.

By learning this distribution, the model can generate new realistic samples.

Examples of generative models include:
- Variational Autoencoders (VAEs)
- Generative Adversarial Networks (GANs)
- GPT models

### Difference Between Generative and Discriminative Models

| Feature | Generative Models | Discriminative Models |
|------|------|------|
| Goal | Generate data | Classify data |
| Probability Learned | P(X,Y) | P(Y|X) |
| Capability | Can generate new samples | Only predicts labels |
| Examples | GAN, VAE, GPT | Logistic Regression, SVM |

In summary, generative models focus on **creating data**, while discriminative models focus on **predicting labels**.

---

# Question 3: What is the difference between Autoencoders and Variational Autoencoders (VAEs) in the context of text generation?

**Answer:**

Autoencoders are neural networks designed to learn compressed representations of input data and reconstruct the original input.

### Structure of an Autoencoder

Input → Encoder → Latent Space → Decoder → Output

The encoder compresses the input into a lower-dimensional representation called the **latent vector**, and the decoder reconstructs the original input.

However, standard autoencoders have limitations when used for generation because their latent space is not structured.

### Variational Autoencoders (VAEs)

Variational Autoencoders introduce a probabilistic approach to representation learning. Instead of encoding a single latent vector, VAEs encode a **probability distribution** defined by:

- Mean (μ)
- Variance (σ)

A sample is drawn from this distribution and passed to the decoder to generate output.

### Key Differences

| Feature | Autoencoder | Variational Autoencoder |
|------|------|------|
| Latent Representation | Deterministic | Probabilistic |
| Output | Reconstruction only | Reconstruction + generation |
| Latent Space | Unstructured | Smooth and continuous |
| Generative Ability | Limited | Strong |

VAEs are widely used in generative tasks such as **text generation, image generation, and anomaly detection**.

---

# Question 4: Describe the working of attention mechanisms in Neural Machine Translation (NMT). Why are they critical?

**Answer:**

In traditional encoder–decoder models used in Neural Machine Translation, the entire input sentence is compressed into a single fixed-length vector before decoding. This approach struggles with long sentences because important information may be lost.

The **attention mechanism** solves this problem by allowing the decoder to focus on different parts of the input sentence during translation.

### How Attention Works

1. The encoder processes the input sentence and produces hidden states for each word.
2. During decoding, the model calculates attention scores between the current decoder state and all encoder hidden states.
3. These scores are converted into weights.
4. A **context vector** is created as a weighted sum of encoder outputs.
5. The decoder uses this context vector to generate the next translated word.

### Why Attention is Critical

- Handles long sentences effectively
- Improves translation accuracy
- Allows word alignment between languages
- Enables models to focus on relevant words

Attention mechanisms also form the foundation of modern **Transformer architectures**, which power models such as **BERT, GPT, and T5**.

---

# Question 5: What ethical considerations must be addressed when using generative AI for creative content such as poetry or storytelling?

**Answer:**

When using generative AI for creative content, several ethical issues must be considered.

### 1. Copyright and Intellectual Property
AI models are often trained on large datasets that may contain copyrighted material. Generated content might unintentionally replicate existing works.

### 2. Plagiarism
AI-generated poems or stories may resemble previously written works, raising concerns about originality.

### 3. Bias and Fairness
Training data may contain cultural, gender, or racial biases. These biases can appear in generated content.

### 4. Misinformation
Generative AI can produce misleading or false narratives that appear convincing.

### 5. Content Ownership
It may be unclear who owns AI-generated content:
- The user
- The developer
- The dataset creators

### 6. Transparency
Users should be informed when content is AI-generated to maintain trust and accountability.

Responsible AI development requires:
- Bias mitigation techniques
- Ethical data sourcing
- Transparency in AI-generated outputs
- Human oversight

---

# Question 10: Design a creative writing assistant using Generative AI.

**Answer:**

A creative writing assistant can help generate story plots, character descriptions, and narrative ideas using generative AI models.

### Model Selection
Large language models such as:
- GPT
- LLaMA
- T5

These models are effective at generating long-form text and maintaining narrative structure.

### Training Data
Training datasets may include:
- Books
- Short stories
- Movie scripts
- Public domain literature

These datasets help the model learn storytelling patterns and language structures.

### Fine-Tuning
The base language model can be fine-tuned using storytelling datasets to improve:
- Plot development
- Character creation
- Dialogue generation

### Bias Mitigation
Bias can be reduced by:
- Using diverse datasets
- Filtering harmful content
- Applying fairness constraints
- Human moderation

### Evaluation Methods

**Automatic Metrics**
- BLEU
- ROUGE
- Perplexity

**Human Evaluation**
- Creativity
- Story coherence
- Character consistency

### Real-World Challenges
Some practical challenges include:
- Copyright issues in training data
- High computational cost
- Bias in generated stories
- Hallucinations or incorrect facts
- Maintaining long narrative consistency

### Deployment
The system can be deployed through:
- A web application
- API integration
- Interactive prompt-based interface

This allows writers and publishers to generate ideas and improve productivity while maintaining creative control.


---

# Question 8: Implement a simple attention-based encoder-decoder model for English-to-Spanish translation using TensorFlow or PyTorch.

**Answer:**

An attention-based encoder–decoder model is commonly used in Neural Machine Translation (NMT) to translate sentences from one language to another. The architecture consists of three main components: the **encoder**, **attention mechanism**, and **decoder**.

### Encoder

The encoder processes the input English sentence and converts it into a sequence of hidden states.

Typical encoder components:
- Embedding layer (converts words into vectors)
- Recurrent Neural Network (LSTM or GRU)

Example:

English Input Sentence:  
"I love machine learning"

The encoder generates hidden states representing each word in the sentence.

### Attention Mechanism

The attention mechanism allows the decoder to focus on relevant words in the input sentence when generating each output word.

Steps in attention:

1. The decoder produces a hidden state at each step.
2. Attention scores are computed between the decoder state and all encoder hidden states.
3. These scores are converted into weights using a softmax function.
4. A **context vector** is computed as a weighted sum of encoder outputs.
5. The context vector is combined with the decoder state to predict the next word.

This allows the model to dynamically focus on different parts of the input sentence during translation.

### Decoder

The decoder generates the Spanish translation word by word.

Typical decoder components:
- Embedding layer
- LSTM/GRU network
- Attention layer
- Dense output layer with softmax

Example translation:

English:  
"I love machine learning"

Spanish:  
"Yo amo el aprendizaje automático"

### Why Attention Improves Translation

Attention mechanisms provide several advantages:

- Improve translation quality for long sentences
- Maintain alignment between source and target words
- Reduce information loss from fixed-length context vectors
- Enable more accurate word selection during decoding

### Libraries Used for Implementation

The model can be implemented using:

- **TensorFlow / Keras**
- **PyTorch**
- Sequence-to-sequence architectures with attention layers

Modern translation systems such as **Transformers** extend this concept further using **self-attention mechanisms**.

In [1]:
# Question 6: Train a simple Variational Autoencoder (simulation) for text reconstruction

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

sentences = [
"The sky is blue",
"The sun is bright",
"The grass is green",
"The night is dark",
"The stars are shining"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)
padded = pad_sequences(sequences, padding='post')

print("Tokenized Sequences:")
print(padded)

print("\nExplanation:")
print("""
A real VAE would encode these sequences into a latent representation
and reconstruct them using a decoder.

For simplicity, we demonstrate preprocessing which is the first step
before feeding data into a neural VAE model.
""")

print("\nSimulated Reconstruction:")
for s in sentences:
    print("Original:", s)
    print("Reconstructed:", s)

Tokenized Sequences:
[[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]

Explanation:

A real VAE would encode these sequences into a latent representation
and reconstruct them using a decoder.

For simplicity, we demonstrate preprocessing which is the first step
before feeding data into a neural VAE model.


Simulated Reconstruction:
Original: The sky is blue
Reconstructed: The sky is blue
Original: The sun is bright
Reconstructed: The sun is bright
Original: The grass is green
Reconstructed: The grass is green
Original: The night is dark
Reconstructed: The night is dark
Original: The stars are shining
Reconstructed: The stars are shining


In [2]:
# Question 7: Use a pre-trained model to translate a short English paragraph
# into French and German.

# Install required libraries
!pip install transformers sentencepiece torch -q

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# English paragraph
text = "Artificial Intelligence is transforming the world by enabling machines to learn from data and assist humans."

# -------------------------
# English → French
# -------------------------
model_name_fr = "Helsinki-NLP/opus-mt-en-fr"

tokenizer_fr = AutoTokenizer.from_pretrained(model_name_fr)
model_fr = AutoModelForSeq2SeqLM.from_pretrained(model_name_fr)

inputs_fr = tokenizer_fr(text, return_tensors="pt", padding=True)
outputs_fr = model_fr.generate(**inputs_fr)

translation_fr = tokenizer_fr.decode(outputs_fr[0], skip_special_tokens=True)

# -------------------------
# English → German
# -------------------------
model_name_de = "Helsinki-NLP/opus-mt-en-de"

tokenizer_de = AutoTokenizer.from_pretrained(model_name_de)
model_de = AutoModelForSeq2SeqLM.from_pretrained(model_name_de)

inputs_de = tokenizer_de(text, return_tensors="pt", padding=True)
outputs_de = model_de.generate(**inputs_de)

translation_de = tokenizer_de.decode(outputs_de[0], skip_special_tokens=True)

# -------------------------
# Print Results
# -------------------------

print("Original Text:")
print(text)

print("\nFrench Translation:")
print(translation_fr)

print("\nGerman Translation:")
print(translation_de)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")


Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning


Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning


Original Text:
Artificial Intelligence is transforming the world by enabling machines to learn from data and assist humans.

French Translation:
L'intelligence artificielle transforme le monde en permettant aux machines d'apprendre des données et d'aider les humains.

German Translation:
Künstliche Intelligenz transformiert die Welt, indem sie Maschinen ermöglicht, aus Daten zu lernen und Menschen zu helfen.


In [3]:
# Question 9: Use the following short poetry dataset to simulate poem generation
# with a pre-trained GPT model.

# Install required library
!pip install transformers torch -q

from transformers import pipeline, set_seed

# Load GPT-2 text generation pipeline
generator = pipeline("text-generation", model="gpt2")

# Prompt based on the given poetry dataset structure
prompt = """
Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
"""

# Generate poem
set_seed(42)
poem = generator(prompt, max_length=40, num_return_sequences=1)

print("Prompt Used:\n")
print(prompt)

print("\nGenerated Poem:\n")
print(poem[0]['generated_text'])

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Passing `generation_config` together with generation-related arguments=({'max_length', 'num_return_sequences'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=40) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


Prompt Used:


Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,


Generated Poem:


Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
The stars are a little red in the night,
The stars are like a light in the darkness.
So here is the way that I have always had it in me to see the world.
In the world as it has always been,
The moon shines red, the stars are a little red in the night,
The stars are like a light in the darkness.
So here is the way that I have always had it in me to see the world.
In the world as it has always been,
The moon shines red, the stars are a little red in the night,
The stars are like a light in the dark.
So here is the way that I have always had it in me to see the world.
In the world as it has always been,
The moon shines red, the stars are a little red in the night,
The stars are like a light in the darkness.
So here is the way that I have always had i